export const dummyUser = {
	id: 1,
	name: 'Captain Duck',
	email: 'captainduck@duck.com',
	image: '/images/profile.png',
	bio: 'I am captain duck and I love to travel and explore new places. I am always up for a challenge and ready to take on any adventure. I am a true explorer and always seeking new experiences. I am a lifelong learner and always eager to learn new things. I am a kind and compassionate person and always strive to make the world a better place. I am a true captain and ready to take on any challenge. I am Captain Duck.',
	groups: [],
	permissions: [],
	dateJoined: '2023-01-01',
	lastLogin: '2023-01-01',
	dateOfBirth: '2023-01-01',
	gender: 'Male',
	age: 30,
	address: '123 Main St, Anytown, USA',
	phone: '123-456-7890',
	website: 'https://duck.com',
	avatar: '/images/profile.png',
	banner: '/images/banner.png',
	profilePicture: '/images/profile.png',
	coverPicture: '/images/cover.webp',
	socialLinks: [],
	languages: [],
	interests: [],
	followers: 12500,
	following: 32,
	tokensEarned: 55,
	totalNotesCreated: 130,
	totalSlateBoardsCreated: 10,
}
